import { getTableConfig, type PgTable } from 'drizzle-orm/pg-core';

import * as schema from '../schema';

/**
 * Every editable entity, in one place: the table it writes, the tRPC router that serves it,
 * and the columns worth showing in a list. The admin pages are generic over this — adding an
 * entity is one entry here, not a new page.
 */

export type EntityGroup = 'Taxonomy' | 'Silicon' | 'Products' | 'Claims' | 'Provenance';

export type EntityDefinition = {
  slug: string;
  label: string;
  group: EntityGroup;
  /** Key of the router in the root router (see `server/trpc.ts`). */
  routerKey: string;
  table: PgTable;
  /** Column shown as this row's name when another entity references it. */
  labelField: string;
  /** Columns rendered in the list, in order. */
  listColumns: readonly string[];
  /** Column that ties this row to its owner, so the list can be filtered to one parent. */
  parentField?: string;
  hint?: string;
};

const define = (definitions: readonly EntityDefinition[]) => definitions;

export const ENTITIES = define([
  // ── Taxonomy ──────────────────────────────────────────────────────────────────────────
  {
    slug: 'manufacturers',
    label: 'Manufacturers',
    group: 'Taxonomy',
    routerKey: 'manufacturers',
    table: schema.manufacturer,
    labelField: 'name',
    listColumns: ['name', 'slug', 'countryCode', 'designsSilicon', 'designsProducts'],
    hint: 'Start here — silicon and products both require a manufacturer.',
  },
  {
    slug: 'architectures',
    label: 'Architectures (ISA)',
    group: 'Taxonomy',
    routerKey: 'architectures',
    table: schema.architecture,
    labelField: 'name',
    listColumns: ['name', 'slug', 'family', 'profile', 'bits'],
  },
  {
    slug: 'core-designs',
    label: 'Core designs',
    group: 'Taxonomy',
    routerKey: 'coreDesigns',
    table: schema.coreDesign,
    labelField: 'name',
    listColumns: ['name', 'kind', 'architectureId', 'executionOrder', 'maxClockMhz'],
    parentField: 'architectureId',
    hint: 'Cortex-A76, XuanTie E902, PowerVR BXM — reusable engine designs that silicon points at.',
  },
  {
    slug: 'form-factors',
    label: 'Form factors',
    group: 'Taxonomy',
    routerKey: 'formFactors',
    table: schema.formFactor,
    labelField: 'name',
    listColumns: ['name', 'standardBody', 'widthMm', 'lengthMm'],
  },
  {
    slug: 'connector-standards',
    label: 'Connector standards',
    group: 'Taxonomy',
    routerKey: 'connectorStandards',
    table: schema.connectorStandard,
    labelField: 'name',
    listColumns: ['name', 'kind', 'pinCount', 'signalVoltageMv'],
  },
  {
    slug: 'software-platforms',
    label: 'Software platforms',
    group: 'Taxonomy',
    routerKey: 'softwarePlatforms',
    table: schema.softwarePlatform,
    labelField: 'name',
    listColumns: ['name', 'kind', 'vendorId', 'isOpenSource'],
  },

  // ── Silicon ───────────────────────────────────────────────────────────────────────────
  {
    slug: 'silicon',
    label: 'Silicon',
    group: 'Silicon',
    routerKey: 'siliconEntity',
    table: schema.silicon,
    labelField: 'name',
    listColumns: ['name', 'slug', 'kind', 'manufacturerId', 'partFamily', 'processNodeNm'],
    parentField: 'manufacturerId',
    hint: 'The chip itself. Everything it can do is added as child rows below.',
  },
  {
    slug: 'silicon-compute-units',
    label: 'Compute units',
    group: 'Silicon',
    routerKey: 'siliconComputeUnits',
    table: schema.siliconComputeUnit,
    labelField: 'label',
    listColumns: [
      'siliconId',
      'kind',
      'role',
      'coreDesignId',
      'coreCount',
      'maxClockMhz',
      'alternativeGroup',
    ],
    parentField: 'siliconId',
    hint: 'One row per engine. Give mutually exclusive engines the same alternative group.',
  },
  {
    slug: 'accelerator-performance',
    label: 'Accelerator throughput',
    group: 'Silicon',
    routerKey: 'acceleratorPerformance',
    table: schema.siliconAcceleratorPerformance,
    labelField: 'value',
    listColumns: ['computeUnitId', 'precision', 'value', 'unit', 'isVendorClaim'],
    parentField: 'computeUnitId',
    hint: 'Attaches to a compute unit, never to the chip — and always with a precision.',
  },
  {
    slug: 'accelerator-precisions',
    label: 'Accelerator precisions',
    group: 'Silicon',
    routerKey: 'acceleratorPrecisions',
    table: schema.siliconAcceleratorPrecision,
    labelField: 'precision',
    listColumns: ['computeUnitId', 'precision'],
    parentField: 'computeUnitId',
  },
  {
    slug: 'silicon-variants',
    label: 'Silicon variants',
    group: 'Silicon',
    routerKey: 'siliconVariants',
    table: schema.siliconVariant,
    labelField: 'orderingCode',
    listColumns: ['siliconId', 'orderingCode', 'temperatureGrade', 'packageType', 'pinCount'],
    parentField: 'siliconId',
    hint: 'Orderable part numbers — grade, package, flash and pin count live here.',
  },
  {
    slug: 'silicon-memory',
    label: 'Memory support',
    group: 'Silicon',
    routerKey: 'siliconMemorySupport',
    table: schema.siliconMemorySupport,
    labelField: 'standard',
    listColumns: ['siliconId', 'kind', 'standard', 'mounting', 'capacityMb', 'maxCapacityMb'],
    parentField: 'siliconId',
  },
  {
    slug: 'silicon-interfaces',
    label: 'Interfaces (capability)',
    group: 'Silicon',
    routerKey: 'siliconInterfaces',
    table: schema.siliconInterface,
    labelField: 'version',
    listColumns: ['siliconId', 'kind', 'count', 'version', 'lanes', 'maxSpeedMbps'],
    parentField: 'siliconId',
    hint: 'What the die provides. What a board routes out is under Products.',
  },
  {
    slug: 'silicon-codecs',
    label: 'Video codecs',
    group: 'Silicon',
    routerKey: 'siliconMediaCodecs',
    table: schema.siliconMediaCodec,
    labelField: 'format',
    listColumns: ['siliconId', 'format', 'direction', 'maxWidth', 'maxHeight', 'maxFps'],
    parentField: 'siliconId',
    hint: 'One row per format per direction — encode and decode are not the same capability.',
  },
  {
    slug: 'silicon-isps',
    label: 'Image signal processors',
    group: 'Silicon',
    routerKey: 'siliconIsps',
    table: schema.siliconIsp,
    labelField: 'generation',
    listColumns: ['siliconId', 'generation', 'maxSensorMp', 'maxLanes', 'maxConcurrentSensors'],
    parentField: 'siliconId',
  },
  {
    slug: 'silicon-radios',
    label: 'Radios',
    group: 'Silicon',
    routerKey: 'siliconRadios',
    table: schema.siliconRadio,
    labelField: 'generation',
    listColumns: ['siliconId', 'standard', 'generation', 'specName', 'bands'],
    parentField: 'siliconId',
  },
  {
    slug: 'silicon-security',
    label: 'Security features',
    group: 'Silicon',
    routerKey: 'siliconSecurityFeatures',
    table: schema.siliconSecurityFeature,
    labelField: 'kind',
    listColumns: ['siliconId', 'kind', 'detail'],
    parentField: 'siliconId',
  },

  // ── Products ──────────────────────────────────────────────────────────────────────────
  {
    slug: 'products',
    label: 'Products',
    group: 'Products',
    routerKey: 'productEntity',
    table: schema.product,
    labelField: 'name',
    listColumns: ['name', 'slug', 'tier', 'manufacturerId', 'familyName'],
    parentField: 'manufacturerId',
    hint: 'Chips, modules, SoMs, boards, carriers and kits — the tier tells them apart.',
  },
  {
    slug: 'product-silicon',
    label: 'Product ↔ silicon',
    group: 'Products',
    routerKey: 'productSilicon',
    table: schema.productSilicon,
    labelField: 'role',
    listColumns: ['productId', 'siliconId', 'role', 'interconnect', 'quantity'],
    parentField: 'productId',
    hint: 'A board holds several chips. The role decides which one answers a given question.',
  },
  {
    slug: 'product-variants',
    label: 'Product variants',
    group: 'Products',
    routerKey: 'productVariants',
    table: schema.productVariant,
    labelField: 'name',
    listColumns: ['productId', 'name', 'sku', 'ramMb', 'storageMb', 'regionCode'],
    parentField: 'productId',
    hint: 'The orderable SKU. Prices and offers will attach here, never to the product.',
  },
  {
    slug: 'product-exposed-interfaces',
    label: 'Exposed interfaces',
    group: 'Products',
    routerKey: 'productExposedInterfaces',
    table: schema.productExposedInterface,
    labelField: 'kind',
    listColumns: [
      'productId',
      'kind',
      'count',
      'version',
      'providedBySiliconId',
      'connectorDescription',
    ],
    parentField: 'productId',
    hint: 'What actually reaches a connector — compared against silicon capability on the product page.',
  },
  {
    slug: 'product-compositions',
    label: 'Composition',
    group: 'Products',
    routerKey: 'productCompositions',
    table: schema.productComposition,
    labelField: 'relation',
    listColumns: ['parentProductId', 'childProductId', 'relation', 'quantity'],
    parentField: 'parentProductId',
    hint: 'Module inside a board, carrier for a module, kit bundling both.',
  },
  {
    slug: 'product-memory',
    label: 'Fitted memory',
    group: 'Products',
    routerKey: 'productMemory',
    table: schema.productMemory,
    labelField: 'standard',
    listColumns: ['productId', 'variantId', 'kind', 'standard', 'mounting', 'capacityMb'],
    parentField: 'productId',
  },
  {
    slug: 'product-storage',
    label: 'Storage',
    group: 'Products',
    routerKey: 'productStorage',
    table: schema.productStorage,
    labelField: 'kind',
    listColumns: ['productId', 'kind', 'interfaceSpec', 'capacityMb', 'isRemovable', 'isBootable'],
    parentField: 'productId',
  },
  {
    slug: 'product-connectors',
    label: 'Connectors',
    group: 'Products',
    routerKey: 'productConnectors',
    table: schema.productConnector,
    labelField: 'name',
    listColumns: ['productId', 'name', 'connectorStandardId', 'quantity', 'pinCount'],
    parentField: 'productId',
  },
  {
    slug: 'product-links',
    label: 'Links',
    group: 'Products',
    routerKey: 'productLinks',
    table: schema.productLink,
    labelField: 'url',
    listColumns: ['productId', 'kind', 'label', 'url', 'isPrimary', 'isBroken'],
    parentField: 'productId',
    hint: 'Many per product — the vendor page, the wiki, the schematic, the shops that stock it.',
  },
  {
    slug: 'price-estimates',
    label: 'Price estimates',
    group: 'Products',
    routerKey: 'priceEstimates',
    table: schema.priceEstimate,
    labelField: 'countryCode',
    listColumns: [
      'productId',
      'variantId',
      'countryCode',
      'currencyCode',
      'amountMinor',
      'kind',
      'asOf',
    ],
    parentField: 'productId',
    hint: 'One indicative price per country, in minor units (5999 = 59.99). Not an offer table — live vendor pricing comes later.',
  },
  {
    slug: 'product-images',
    label: 'Images',
    group: 'Products',
    routerKey: 'productImages',
    table: schema.productImage,
    labelField: 'alt',
    listColumns: ['productId', 'kind', 'alt', 'storageKey', 'isPrimary', 'sortOrder'],
    parentField: 'productId',
    hint: 'Mirrored locally so the catalog survives a vendor reorganising their site.',
  },
  {
    slug: 'operating-modes',
    label: 'Operating modes',
    group: 'Products',
    routerKey: 'operatingModes',
    table: schema.operatingMode,
    labelField: 'name',
    listColumns: [
      'productId',
      'name',
      'powerBudgetW',
      'activeCpuCores',
      'cpuClockCapMhz',
      'isDefault',
    ],
    parentField: 'productId',
    hint: '7 W / 15 W / 25 W — every performance figure must reference one of these.',
  },
  {
    slug: 'product-power',
    label: 'Power inputs',
    group: 'Products',
    routerKey: 'productPower',
    table: schema.productPower,
    labelField: 'inputKind',
    listColumns: ['productId', 'inputKind', 'voltageMinMv', 'voltageMaxMv', 'recommendedSupplyW'],
    parentField: 'productId',
  },
  {
    slug: 'product-power-draw',
    label: 'Power draw',
    group: 'Products',
    routerKey: 'productPowerDraw',
    table: schema.productPowerDraw,
    labelField: 'scenario',
    listColumns: ['productId', 'operatingModeId', 'scenario', 'powerW', 'isMeasured'],
    parentField: 'productId',
  },
  {
    slug: 'product-antennas',
    label: 'Antennas',
    group: 'Products',
    routerKey: 'productAntennas',
    table: schema.productAntenna,
    labelField: 'type',
    listColumns: ['productId', 'type', 'connector', 'gainDbi', 'isIncluded'],
    parentField: 'productId',
  },
  {
    slug: 'product-certifications',
    label: 'Certifications',
    group: 'Products',
    routerKey: 'productCertifications',
    table: schema.productCertification,
    labelField: 'identifier',
    listColumns: ['productId', 'authority', 'identifier', 'scope', 'issuedAt'],
    parentField: 'productId',
  },
  {
    slug: 'product-form-factors',
    label: 'Form factor conformance',
    group: 'Products',
    routerKey: 'productFormFactors',
    table: schema.productFormFactor,
    labelField: 'conformance',
    listColumns: ['productId', 'formFactorId', 'conformance'],
    parentField: 'productId',
  },
  {
    slug: 'product-environments',
    label: 'Environmental limits',
    group: 'Products',
    routerKey: 'productEnvironments',
    table: schema.productEnvironment,
    labelField: 'ingressRating',
    listColumns: ['productId', 'operatingTempMinC', 'operatingTempMaxC', 'ingressRating'],
    parentField: 'productId',
  },
  {
    slug: 'product-revisions',
    label: 'Revisions',
    group: 'Products',
    routerKey: 'productRevisions',
    table: schema.productRevision,
    labelField: 'revision',
    listColumns: ['productId', 'revision', 'releasedAt', 'summary'],
    parentField: 'productId',
  },

  // ── Claims ────────────────────────────────────────────────────────────────────────────
  {
    slug: 'compatibility-claims',
    label: 'Compatibility',
    group: 'Claims',
    routerKey: 'compatibilityClaims',
    table: schema.compatibilityClaim,
    labelField: 'summary',
    listColumns: ['subjectProductId', 'targetProductId', 'level', 'summary'],
    parentField: 'subjectProductId',
    hint: 'Graded, never a boolean — the per-signal exceptions go in the deltas below.',
  },
  {
    slug: 'compatibility-deltas',
    label: 'Compatibility deltas',
    group: 'Claims',
    routerKey: 'compatibilityDeltas',
    table: schema.compatibilityDelta,
    labelField: 'signal',
    listColumns: ['claimId', 'signal', 'subjectFunction', 'targetFunction', 'impact'],
    parentField: 'claimId',
  },
  {
    slug: 'software-support',
    label: 'Software support',
    group: 'Claims',
    routerKey: 'softwareSupportClaims',
    table: schema.softwareSupportClaim,
    labelField: 'component',
    listColumns: ['productId', 'siliconId', 'softwarePlatformId', 'component', 'level', 'source'],
    parentField: 'productId',
    hint: 'Per component. A board-level "Linux: supported" is the field that misleads most.',
  },
  {
    slug: 'lifecycle-events',
    label: 'Lifecycle events',
    group: 'Claims',
    routerKey: 'lifecycleEvents',
    table: schema.lifecycleEvent,
    labelField: 'state',
    listColumns: ['productId', 'siliconId', 'state', 'effectiveAt', 'summary'],
    parentField: 'productId',
  },
  {
    slug: 'longevity',
    label: 'Longevity commitments',
    group: 'Claims',
    routerKey: 'longevityCommitments',
    table: schema.longevityCommitment,
    labelField: 'scope',
    listColumns: ['productId', 'siliconId', 'scope', 'guaranteedUntil', 'isMinimum'],
    parentField: 'productId',
  },

  // ── Provenance ────────────────────────────────────────────────────────────────────────
  {
    slug: 'sources',
    label: 'Sources',
    group: 'Provenance',
    routerKey: 'sources',
    table: schema.source,
    labelField: 'title',
    listColumns: ['title', 'type', 'publisher', 'url', 'retrievedAt'],
    hint: 'Datasheets, product pages, errata. Every fact row can cite one.',
  },
  {
    slug: 'claims',
    label: 'Claims',
    group: 'Provenance',
    routerKey: 'claims',
    table: schema.claim,
    labelField: 'valueText',
    listColumns: ['entityTable', 'entityId', 'fieldPath', 'valueText', 'status', 'confidence'],
  },
  {
    slug: 'change-proposals',
    label: 'Change proposals',
    group: 'Provenance',
    routerKey: 'changeProposals',
    table: schema.changeProposal,
    labelField: 'title',
    listColumns: ['title', 'status', 'authorKind', 'agentRunId', 'appliedAt'],
  },
  {
    slug: 'research-tasks',
    label: 'Research tasks',
    group: 'Provenance',
    routerKey: 'researchTasks',
    table: schema.researchTask,
    labelField: 'subject',
    listColumns: ['subject', 'status', 'assignedTo', 'priority', 'completedAt'],
  },
]);

export const ENTITY_GROUPS: readonly EntityGroup[] = [
  'Taxonomy',
  'Silicon',
  'Products',
  'Claims',
  'Provenance',
];

export const findEntity = (slug: string): EntityDefinition | undefined =>
  ENTITIES.find((entity) => entity.slug === slug);

/** SQL table name → admin slug, so a foreign key can be rendered as a picker. */
const ENTITY_BY_TABLE = new Map(
  ENTITIES.map((entity) => [getTableConfig(entity.table).name, entity.slug]),
);

export const entitySlugForTable = (sqlTableName: string): string | undefined =>
  ENTITY_BY_TABLE.get(sqlTableName);
