#!/usr/bin/env node
// Vite-SPA variant of the gating lab: generate src/generated/routes.ts that statically imports only enabled
// features, so Rollup drops the rest. Reuses the parent app's feature manifests + profiles.
// Usage:
//   node gate.mjs --profile minimal [--runtime react|preact] [--build]
//   node gate.mjs --features overview,workflow --runtime preact --build

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const PARENT = path.join(ROOT, '..');
const FEATURES_DIR = path.join(PARENT, 'app/src/features');
const ROUTES_FILE = path.join(ROOT, 'src/generated/routes.ts');

function parseArgs(argv) {
  const args = { runtime: 'react', build: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--profile') args.profile = argv[++i];
    else if (a === '--features') args.features = argv[++i];
    else if (a === '--runtime') args.runtime = argv[++i];
    else if (a === '--build') args.build = true;
  }
  return args;
}

function loadFeatures() {
  const map = new Map();
  for (const id of fs.readdirSync(FEATURES_DIR)) {
    const manifest = path.join(FEATURES_DIR, id, 'feature.json');
    if (fs.existsSync(manifest)) map.set(id, JSON.parse(fs.readFileSync(manifest, 'utf8')));
  }
  return map;
}

function resolveEnabled(args, features) {
  let ids;
  if (args.features) ids = args.features.split(',').map((s) => s.trim()).filter(Boolean);
  else {
    const profiles = JSON.parse(fs.readFileSync(path.join(PARENT, 'profiles.json'), 'utf8'));
    if (!args.profile || !profiles[args.profile]) {
      throw new Error(`unknown profile "${args.profile}". Known: ${Object.keys(profiles).join(', ')}`);
    }
    ids = profiles[args.profile];
  }
  for (const id of ids) if (!features.has(id)) throw new Error(`unknown feature "${id}"`);
  return ids;
}

function comp(id) {
  return id.charAt(0).toUpperCase() + id.slice(1).replace(/[^a-zA-Z0-9]/g, '');
}

function writeRoutes(profileLabel, enabled, features) {
  const imports = enabled.map((id) => `import ${comp(id)} from '@features/${id}/impl';`).join('\n');
  const rows = enabled
    .map((id) => features.get(id))
    .map(
      (m) =>
        `  { route: '${m.route}', label: ${JSON.stringify(m.label)}, heavy: ${m.heavy}, Component: ${comp(m.id)} },`,
    )
    .join('\n');
  fs.mkdirSync(path.dirname(ROUTES_FILE), { recursive: true });
  fs.writeFileSync(
    ROUTES_FILE,
    `// AUTO-GENERATED by gate.mjs — do not edit.\n` +
      `import type { ComponentType } from 'react';\n${imports}\n\n` +
      `export const PROFILE = ${JSON.stringify(profileLabel)};\n\n` +
      `export interface RouteDef { route: string; label: string; heavy: boolean; Component: ComponentType }\n\n` +
      `export const ROUTES: RouteDef[] = [\n${rows}\n];\n`,
  );
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const features = loadFeatures();
  const enabled = resolveEnabled(args, features);
  const profileLabel = args.profile ?? enabled.join('+');

  writeRoutes(profileLabel, enabled, features);
  console.log(`[gate] runtime=${args.runtime} profile=${profileLabel} enabled=[${enabled.join(', ')}]`);

  if (args.build) {
    fs.rmSync(path.join(ROOT, 'dist'), { recursive: true, force: true });
    const res = spawnSync('npx', ['vite', 'build'], {
      cwd: ROOT,
      stdio: 'inherit',
      env: { ...process.env, HELIX_RUNTIME: args.runtime },
    });
    if (res.status !== 0) process.exit(res.status ?? 1);
  }
}

main();
