// SPDX-License-Identifier: AGPL-3.0-only

package runtimemanager

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/helix-kit/helix-device/internal/pkg"
	"github.com/helix-kit/helix-device/internal/shared/config"
)

// unitPath is where a service's generated unit is written.
func unitPath(d *pkg.ServiceDescriptor) string {
	return filepath.Join(config.SystemdUnitDir(), d.UnitName())
}

// RenderUnit produces the systemd unit for a managed service; output is deterministic (sorted Environment keys).
func RenderUnit(d *pkg.ServiceDescriptor) string {
	var b strings.Builder
	b.WriteString("# Generated by helix-runtime-manager. Do not edit.\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=Helix service %s\n", d.Name)
	after := append([]string{"network-online.target"}, d.After...)
	fmt.Fprintf(&b, "After=%s\n", strings.Join(after, " "))
	if len(d.Requires) > 0 {
		fmt.Fprintf(&b, "Requires=%s\n", strings.Join(d.Requires, " "))
	}

	b.WriteString("\n[Service]\n")
	b.WriteString("Type=simple\n")
	if d.User != "" {
		fmt.Fprintf(&b, "User=%s\n", d.User)
	}
	if d.Group != "" {
		fmt.Fprintf(&b, "Group=%s\n", d.Group)
	}
	if d.WorkingDirectory != "" {
		fmt.Fprintf(&b, "WorkingDirectory=%s\n", d.WorkingDirectory)
	}
	for _, ef := range d.EnvironmentFiles {
		// '-' makes a missing secret file non-fatal.
		fmt.Fprintf(&b, "EnvironmentFile=-%s\n", ef)
	}
	for _, k := range sortedKeys(d.Environment) {
		fmt.Fprintf(&b, "Environment=%s=%s\n", k, d.Environment[k])
	}
	fmt.Fprintf(&b, "ExecStart=%s\n", strings.Join(d.ExecStart, " "))
	fmt.Fprintf(&b, "Restart=%s\n", orDefault(d.Restart, "on-failure"))
	fmt.Fprintf(&b, "RestartSec=%d\n", orDefaultInt(d.RestartSec, 2))

	b.WriteString("\n[Install]\n")
	wantedBy := d.WantedBy
	if len(wantedBy) == 0 {
		wantedBy = []string{"helix.target"}
	}
	fmt.Fprintf(&b, "WantedBy=%s\n", strings.Join(wantedBy, " "))
	return b.String()
}

// WriteUnit renders and atomically writes a service's unit file, returning whether it changed.
func WriteUnit(d *pkg.ServiceDescriptor) (changed bool, err error) {
	content := RenderUnit(d)
	path := unitPath(d)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return false, err
	}
	if err := os.Rename(tmp, path); err != nil {
		return false, err
	}
	return true, nil
}

// RemoveUnit deletes a service's generated unit file.
func RemoveUnit(name string) error {
	path := filepath.Join(config.SystemdUnitDir(), "helix-"+name+".service")
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func sortedKeys(m map[string]string) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

func orDefaultInt(v, def int) int {
	if v == 0 {
		return def
	}
	return v
}
