#!/usr/bin/env node
// Prepare the Next.js app for a given enabled-feature set, then optionally build it as a static export.
//   --approach filesystem  materialize ONLY enabled routes (bundler drops disabled routes + deps; bundler-agnostic).
//   --approach stubbing     materialize ALL routes, pass HELIX_GATED_OUT so webpack stubs disabled features' ./impl.
// Usage:
//   node gate.mjs --profile minimal [--approach filesystem|stubbing] [--build]
//   node gate.mjs --features overview,workflow --build

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const APP = path.join(ROOT, 'app');
const FEATURES_DIR = path.join(APP, 'src/features');
const GEN_ROUTES = path.join(APP, 'src/app/(gen)');
const ALL_ROUTES = path.join(APP, 'src/app/(all)');
const NAV_FILE = path.join(APP, 'src/generated/nav.ts');

function parseArgs(argv) {
  const args = { approach: 'filesystem', build: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--profile') args.profile = argv[++i];
    else if (a === '--features') args.features = argv[++i];
    else if (a === '--approach') args.approach = argv[++i];
    else if (a === '--build') args.build = true;
  }
  return args;
}

function loadFeatures() {
  const map = new Map();
  for (const id of fs.readdirSync(FEATURES_DIR)) {
    const manifest = path.join(FEATURES_DIR, id, 'feature.json');
    if (!fs.existsSync(manifest)) continue;
    const meta = JSON.parse(fs.readFileSync(manifest, 'utf8'));
    map.set(meta.id, meta);
  }
  return map;
}

function resolveEnabled(args, features) {
  let ids;
  if (args.features) ids = args.features.split(',').map((s) => s.trim()).filter(Boolean);
  else {
    const profiles = JSON.parse(fs.readFileSync(path.join(ROOT, 'profiles.json'), 'utf8'));
    if (!args.profile || !profiles[args.profile]) {
      throw new Error(`unknown profile "${args.profile}". Known: ${Object.keys(profiles).join(', ')}`);
    }
    ids = profiles[args.profile];
  }
  for (const id of ids) if (!features.has(id)) throw new Error(`unknown feature "${id}"`);
  return ids;
}

function rmrf(p) {
  fs.rmSync(p, { recursive: true, force: true });
}

function writeRoute(baseDir, route, importSpec) {
  const folder = path.join(baseDir, route.replace(/^\//, ''));
  fs.mkdirSync(folder, { recursive: true });
  fs.writeFileSync(
    path.join(folder, 'page.tsx'),
    `// AUTO-GENERATED by gate.mjs — do not edit.\nexport { default } from '${importSpec}';\n`,
  );
}

function writeNav(profileLabel, enabled, features) {
  const items = enabled
    .map((id) => features.get(id))
    .map((m) => `  { route: '${m.route}', label: ${JSON.stringify(m.label)}, heavy: ${m.heavy} },`)
    .join('\n');
  fs.mkdirSync(path.dirname(NAV_FILE), { recursive: true });
  fs.writeFileSync(
    NAV_FILE,
    `// AUTO-GENERATED by gate.mjs — do not edit.\n` +
      `import type { NavItem } from '@/lib/nav-types';\n\n` +
      `export const PROFILE = ${JSON.stringify(profileLabel)};\n\n` +
      `export const NAV: NavItem[] = [\n${items}\n];\n`,
  );
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const features = loadFeatures();
  const enabled = resolveEnabled(args, features);
  const profileLabel = args.profile ?? enabled.join('+');

  writeNav(profileLabel, enabled, features);

  rmrf(GEN_ROUTES);
  rmrf(ALL_ROUTES);

  let env = { ...process.env };
  if (args.approach === 'filesystem') {
    for (const id of enabled) writeRoute(GEN_ROUTES, features.get(id).route, `@/features/${id}/page`);
  } else if (args.approach === 'stubbing') {
    const gatedOut = [];
    for (const [id, meta] of features) {
      writeRoute(ALL_ROUTES, meta.route, `@/features/${id}/page`);
      if (!enabled.includes(id)) gatedOut.push(id);
    }
    env.HELIX_GATED_OUT = gatedOut.join(',');
  } else {
    throw new Error(`unknown approach "${args.approach}"`);
  }

  console.log(
    `[gate] approach=${args.approach} profile=${profileLabel} ` +
      `enabled=[${enabled.join(', ')}]` +
      (env.HELIX_GATED_OUT ? ` gatedOut=[${env.HELIX_GATED_OUT}]` : ''),
  );

  if (args.build) {
    rmrf(path.join(APP, 'out'));
    rmrf(path.join(APP, '.next'));
    const res = spawnSync('npx', ['next', 'build'], { cwd: APP, stdio: 'inherit', env });
    if (res.status !== 0) process.exit(res.status ?? 1);
  }
}

main();
