from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path

_KEY_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=")

BACKUP_SUFFIX = ".bak"


@dataclass(frozen=True)
class AppEnvPlan:
    """The desired `.env` for one web app: `managed` keys resync each start, `defaults` seed once."""

    name: str
    path: Path
    managed: dict[str, str]
    defaults: dict[str, str]

    def render(self) -> str:
        lines = [
            f"# {self.name} — generated by `helix appliance up`.",
            "# The [managed] block is rewritten on every start; edit the rest freely.",
            "",
            "# ---- [managed] wired to the local appliance — do not edit ----",
            *(f"{key}={value}" for key, value in self.managed.items()),
            "",
            "# ---- yours to edit (preserved across restarts) ----",
            *(f"{key}={value}" for key, value in self.defaults.items()),
        ]
        return "\n".join(lines) + "\n"


def _merge_managed(existing: str, managed: dict[str, str]) -> str:
    # Replace/add only the managed keys; every other line is preserved verbatim.
    remaining = dict(managed)
    out: list[str] = []
    for line in existing.splitlines():
        match = _KEY_RE.match(line)
        key = match.group(1) if match else None
        if key is not None and key in remaining:
            out.append(f"{key}={remaining.pop(key)}")
        else:
            out.append(line)
    if remaining:
        if out and out[-1].strip() != "":
            out.append("")
        out.append("# ---- [managed] added by `helix appliance up` ----")
        out.extend(f"{key}={value}" for key, value in remaining.items())
    return "\n".join(out) + "\n"


def write_env(plan: AppEnvPlan, *, fresh: bool) -> str:
    """Write `plan` to disk (fresh backs up + rewrites; otherwise resyncs managed keys only)."""
    plan.path.parent.mkdir(parents=True, exist_ok=True)
    if not plan.path.exists():
        plan.path.write_text(plan.render())
        return "created"
    if fresh:
        backup = plan.path.with_name(plan.path.name + BACKUP_SUFFIX)
        os.replace(plan.path, backup)
        plan.path.write_text(plan.render())
        return f"recreated (backed up to {backup.name})"
    plan.path.write_text(_merge_managed(plan.path.read_text(), plan.managed))
    return "synced"
